// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: cmd/xgotop/storage/event.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PBEvent represents a Go runtime event in protobuf format
type PBEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType       uint64                 `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Goroutine       uint32                 `protobuf:"varint,3,opt,name=goroutine,proto3" json:"goroutine,omitempty"`
	ParentGoroutine uint32                 `protobuf:"varint,4,opt,name=parent_goroutine,json=parentGoroutine,proto3" json:"parent_goroutine,omitempty"`
	Attributes      []uint64               `protobuf:"varint,5,rep,packed,name=attributes,proto3" json:"attributes,omitempty"` // Array of 5 attributes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PBEvent) Reset() {
	*x = PBEvent{}
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEvent) ProtoMessage() {}

func (x *PBEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEvent.ProtoReflect.Descriptor instead.
func (*PBEvent) Descriptor() ([]byte, []int) {
	return file_cmd_xgotop_storage_event_proto_rawDescGZIP(), []int{0}
}

func (x *PBEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PBEvent) GetEventType() uint64 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *PBEvent) GetGoroutine() uint32 {
	if x != nil {
		return x.Goroutine
	}
	return 0
}

func (x *PBEvent) GetParentGoroutine() uint32 {
	if x != nil {
		return x.ParentGoroutine
	}
	return 0
}

func (x *PBEvent) GetAttributes() []uint64 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// PBEventBatch represents a batch of events for efficient storage
type PBEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*PBEvent             `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBEventBatch) Reset() {
	*x = PBEventBatch{}
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBEventBatch) ProtoMessage() {}

func (x *PBEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBEventBatch.ProtoReflect.Descriptor instead.
func (*PBEventBatch) Descriptor() ([]byte, []int) {
	return file_cmd_xgotop_storage_event_proto_rawDescGZIP(), []int{1}
}

func (x *PBEventBatch) GetEvents() []*PBEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// PBSession represents a recording session metadata
type PBSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTimeUnix int64                  `protobuf:"varint,2,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"` // Unix timestamp in nanoseconds
	EndTimeUnix   int64                  `protobuf:"varint,3,opt,name=end_time_unix,json=endTimeUnix,proto3" json:"end_time_unix,omitempty"`       // Unix timestamp in nanoseconds (0 if not ended)
	Pid           int32                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	BinaryPath    string                 `protobuf:"bytes,5,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	EventCount    int64                  `protobuf:"varint,6,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBSession) Reset() {
	*x = PBSession{}
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBSession) ProtoMessage() {}

func (x *PBSession) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBSession.ProtoReflect.Descriptor instead.
func (*PBSession) Descriptor() ([]byte, []int) {
	return file_cmd_xgotop_storage_event_proto_rawDescGZIP(), []int{2}
}

func (x *PBSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PBSession) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *PBSession) GetEndTimeUnix() int64 {
	if x != nil {
		return x.EndTimeUnix
	}
	return 0
}

func (x *PBSession) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PBSession) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *PBSession) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

// PBStorageFile represents the complete storage file format
type PBStorageFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *PBSession             `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Events        []*PBEvent             `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBStorageFile) Reset() {
	*x = PBStorageFile{}
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBStorageFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBStorageFile) ProtoMessage() {}

func (x *PBStorageFile) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_xgotop_storage_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBStorageFile.ProtoReflect.Descriptor instead.
func (*PBStorageFile) Descriptor() ([]byte, []int) {
	return file_cmd_xgotop_storage_event_proto_rawDescGZIP(), []int{3}
}

func (x *PBStorageFile) GetSession() *PBSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *PBStorageFile) GetEvents() []*PBEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_cmd_xgotop_storage_event_proto protoreflect.FileDescriptor

const file_cmd_xgotop_storage_event_proto_rawDesc = "" +
	"\n" +
	"\x1ecmd/xgotop/storage/event.proto\x12\astorage\"\xaf\x01\n" +
	"\aPBEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x04R\teventType\x12\x1c\n" +
	"\tgoroutine\x18\x03 \x01(\rR\tgoroutine\x12)\n" +
	"\x10parent_goroutine\x18\x04 \x01(\rR\x0fparentGoroutine\x12\x1e\n" +
	"\n" +
	"attributes\x18\x05 \x03(\x04R\n" +
	"attributes\"8\n" +
	"\fPBEventBatch\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.storage.PBEventR\x06events\"\xbb\x01\n" +
	"\tPBSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fstart_time_unix\x18\x02 \x01(\x03R\rstartTimeUnix\x12\"\n" +
	"\rend_time_unix\x18\x03 \x01(\x03R\vendTimeUnix\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x05R\x03pid\x12\x1f\n" +
	"\vbinary_path\x18\x05 \x01(\tR\n" +
	"binaryPath\x12\x1f\n" +
	"\vevent_count\x18\x06 \x01(\x03R\n" +
	"eventCount\"g\n" +
	"\rPBStorageFile\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.storage.PBSessionR\asession\x12(\n" +
	"\x06events\x18\x02 \x03(\v2\x10.storage.PBEventR\x06eventsB'Z%go.sazak.io/xgotop/cmd/xgotop/storageb\x06proto3"

var (
	file_cmd_xgotop_storage_event_proto_rawDescOnce sync.Once
	file_cmd_xgotop_storage_event_proto_rawDescData []byte
)

func file_cmd_xgotop_storage_event_proto_rawDescGZIP() []byte {
	file_cmd_xgotop_storage_event_proto_rawDescOnce.Do(func() {
		file_cmd_xgotop_storage_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_xgotop_storage_event_proto_rawDesc), len(file_cmd_xgotop_storage_event_proto_rawDesc)))
	})
	return file_cmd_xgotop_storage_event_proto_rawDescData
}

var file_cmd_xgotop_storage_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_xgotop_storage_event_proto_goTypes = []any{
	(*PBEvent)(nil),       // 0: storage.PBEvent
	(*PBEventBatch)(nil),  // 1: storage.PBEventBatch
	(*PBSession)(nil),     // 2: storage.PBSession
	(*PBStorageFile)(nil), // 3: storage.PBStorageFile
}
var file_cmd_xgotop_storage_event_proto_depIdxs = []int32{
	0, // 0: storage.PBEventBatch.events:type_name -> storage.PBEvent
	2, // 1: storage.PBStorageFile.session:type_name -> storage.PBSession
	0, // 2: storage.PBStorageFile.events:type_name -> storage.PBEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cmd_xgotop_storage_event_proto_init() }
func file_cmd_xgotop_storage_event_proto_init() {
	if File_cmd_xgotop_storage_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_xgotop_storage_event_proto_rawDesc), len(file_cmd_xgotop_storage_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_xgotop_storage_event_proto_goTypes,
		DependencyIndexes: file_cmd_xgotop_storage_event_proto_depIdxs,
		MessageInfos:      file_cmd_xgotop_storage_event_proto_msgTypes,
	}.Build()
	File_cmd_xgotop_storage_event_proto = out.File
	file_cmd_xgotop_storage_event_proto_goTypes = nil
	file_cmd_xgotop_storage_event_proto_depIdxs = nil
}
